Fix the issue that dummy path does not get added
A dummy join is a fast path for the case that we know a join will
produce no output tuple.  For example when the join condition or
prediction conflicts with the relation's constraints there will be no
matching tuples; for many join types if either child, or both, is dummy
join then itself is also dummy join.

In such cases we do not need to join at all, so we mark the join as
dummy join by calling the function mark_dummy_join(), it adds a dummy
path and clear all the previously chosen paths in this order:

    1. clear pathlist;
    2. add the dummy path;
    3. clear deduplication pathlist;

However the problem is that in the second step the dummy path can be
added to the deduplication pathlist under some conditions, so in step 3
the dummy path is cleared too, so the relation will has no path at all,
as a result it might trigger an error like this:

    ERROR: Could not devise a query plan for the given query.

To fix the issue we should swap the steps 2 and 3, first clear both
pathlist and deduplication pathlist, then add the dummy path, so the
dummy path can always be added as the only path.

Co-authored-by: Hubert Zhang <hzhang@pivotal.io>
Co-authored-by: Ning Yu <nyu@pivotal.io>
Reviewed-by: Richard Guo <guofenglinux@gmail.com>