Do not reduce 1:1 motion for full join.
A 1:1 motion will be removed if the sender and receiver are on the same
segment.  However this will cause runtime failure for FULL JOIN.

    -- t1.numsegments = 1
    SELECT * FROM t1 a FULL JOIN t1 b ON TRUE;

    ERROR:  Unexpected internal error (heapam.c:895)
    DETAIL:  FailedAssertion("!(lineoff ==
             scan->rs_vistuples[scan->rs_cindex])", File: "heapam.c",
             Line: 895)

As a workaround we should keep the 1:1 motions in FULL JOIN.