packcore: be more verbose on test failures
The packcore test failed once on the pipeline with below error:

    ERROR:  subprocess.CalledProcessError:
      Command '['tar', '-zxf', 'packcore-core.postgres.tgz']'
      returned non-zero exit status 2
    CONTEXT:  Traceback (most recent call last):
      PL/Python anonymous code block, line 72, in <module>
        corefile])
      PL/Python anonymous code block, line 26, in test_packcore
        subprocess.check_call(['tar', '-zxf', tarball])
      PL/Python anonymous code block, line 540, in check_call
    PL/Python anonymous code block

Unfortunately error details were not included.  So we modified the tests
to dump the stdout & stderr of a failed command, hopefully we could
understand what's really wrong when the error happens in the future.

Also removed one gdb check on the core, we should not assume that we are
testing against a postgres coredump, so do not check any postgres
specific symbol.

(cherry picked from commit de95f09bc2053d6d8c7ad8011e64d3fdb843ede9)