Update cacerts with new repo.pivotal.io cert
The ivy tool uses this cacerts file as the java keystore when it
attempts to create an SSL connection to repo.pivotal.io (jfrog
repositoriy). The file has gone out of date, and requires the newest
certificate for repo.pivotal.io.

The error one should expect in this case is hard to debug unless you
know what to look for:
```
[ivy:resolve] Server access Error:
sun.security.validator.ValidatorException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to
find valid certification path to requested target
url=https://repo.pivotal.io/gpdb-ext-release-local/xerces/xerces-c/3.1.1-p1/ivys/ivy-3.1.1-p1.xml
```

The solution is to grab the newest cert and insert it into the cacert
keystore blob. This was done like so:

```
openssl s_client -showcerts -connect repo.pivotal.io:443 > jfrog.crt
vim jfrog.crt
keytool -importcert -keystore gpdb4/gpAux/releng/make/dependencies/cacerts -storepass changeit -file ./jfrog.crt
```

This is only necessary in GPDB4 because in GPDB5+ there was work to
remove the need to use a java keystore commited to the repository.