Backwards compatibility for `gp_workfile_entries`
In the previous commit, `utility` column was no longer used and removed.
This would work for 5.X but it breaks the schema compatibility for 4.3.

This commit restores the schema of the view
gp_toolkit.gp_workfile_entries, and instead changes the underlying
implementation of the view to return a dummy zero value for the
"utility" output column.

This commit also changes gp_toolkit.sql to explicitly remove 3
(undocumented) functions related to workfile caching. For a cluster that
upgrades to this version without re-running gp_toolkit.sql, calling said
functions would error out like:

```
ERROR:  could not find function "gp_workfile_mgr_clear_cache" in file "/usr/local/gpdb4/lib/postgresql/gp_workfile_mgr.so"
```

Also remove all references of the gp_toolkit functions from tests.

Signed-off-by: Jesse Zhang <sbjesse@gmail.com>
Signed-off-by: Shreedhar Hardikar <shardikar@pivotal.io>